Implementation of XGBoost for Alzheimer's Disease Prediction and Validation of Data Integrity in Model Development
Redback-Operations/redback-senior-tech pull request #120
Opened 2024-11-27 11:27 UTC by Laksh221354136

## What are the changes?

- 

## New Components/Features

- 

## Enhanced Components/Features

- 

## Other Changes/Fixes

- 

## Additional Notes

## Checklist
<!-- 
  [x]Verified that the training and testing data split to avoid to stop data leakage

 [x]The XGBoost model was implemented

[x] tuned XGBoost's hyperparameters and noted down the process.

[x] sourced a new dataset a for testing.

 [x]Used key measures to evaluate and compare Random Forest and XGBoost.
 
## Screenshots or example output
[evidence.pdf](https://github.com/user-attachments/files/17933478/evidence.pdf)

2024-12-08 05:21 UTC, AmirZandiehprojects commented
can you address only the ( PULL REQUEST ) workflow which failed dont worry about the Security Check as that's fixed that and after you made your changes please make another Pull Request thanks !

2024-12-10 13:08 UTC, Thumbness requested changes
A few comments made regarding file types, also, you should rename your directory appropriately to fit the feature work you have implemented (XGBoost maybe) 

Its not appropriate to have a name 'updatetri3' in the repository, as it gives zero context to the contents of the directory'

2024-12-10 13:08 UTC, Thumbness commented on data_science/alzheimers_prediction/updatetri3/data source.docx
You should move this into the README.md file, as it gives context to what the data source is. Try and consolidate details of the directory in one README.md :)

2024-12-10 13:08 UTC, Thumbness commented on data_science/alzheimers_prediction/updatetri3/xgboost.docx
Same goes for here Laksh, we dont support docx or pdf in repositories!, Move these details into the README.md under a topic header

2024-12-17 09:02 UTC, Ashan224019868 reviewed
LGTM - MANUALLY REVIEWED | NO SECURITY ISSUES

2025-01-21 03:19 UTC, merged