Dataset for the dashboard
Redback-Operations/redback-senior-tech pull request #56
Opened 2024-08-17 13:43 UTC by jananibabu3

## What are the changes?

## Who worked on the changes?

- 

## New Components/Features

- 

## Enhanced Components/Features

- 

## Other Changes/Fixes

- 

## Additional Notes

## TODOs

- [ ] Example Checkbox

## Checklist

- [ ] Existing, relevant documentation has been updated to reflect my changes 

## Screenshots or example output

2024-08-20 08:36 UTC, Manan2711 commented
Hi @jananibabu3, can you please make the following changes:

1. Please add the data file into a subfolder rather than adding it directly into the "Health Monitoring Dashboard" folder.
2. In the data folder please add a markdown file that provides the following details:
\- The units in which the data is recorded, for example celsius for temperature columns and so on.
\- Just a short description of the dataset – where it was sourced from (add a link to the source), what each columns are about, etc.
4. In main README.md file (the one in "Health Monitoring Dashboard" folder) – please include a short description on what the feature is about, folder structure, etc rather than short updates. Please refer to [this](https://deakin365.sharepoint.com/:t:/r/sites/RedbackOperations9/Shared%20Documents/Project%202%20-%20Elderly%20Wearable%20Technology/[README_TEMPLATE.MD](https://deakin365.sharepoint.com/:t:/r/sites/RedbackOperations9/Shared%20Documents/Project%202%20-%20Elderly%20Wearable%20Technology/README_TEMPLATE.MD?csf=1&web=1&e=98jIYI)?csf=1&web=1&e=98jIYI) markdown file to get ideas on what to include in the readme file.

2024-08-27 11:42 UTC, ben-AI-cybersec commented
No code, just data - doesn't require secdevops review.

2024-08-29 02:43 UTC, Manan2711 requested changes

2024-08-29 02:43 UTC, Manan2711 commented on Data Science/Health Monitoring Dashboard/HealthData.xlsx
I suppose this file was accidently added to the main folder as well. Can you please delete this file from here?

2024-08-29 02:43 UTC, Manan2711 commented on Data Science/Health Monitoring Dashboard/Dataset/sensor data
Was this file added accidently? It's an empty file, can you please check this one too.

2024-08-29 03:42 UTC, jananibabu3 commented on Data Science/Health Monitoring Dashboard/Dataset/sensor data
Updated now!

2024-08-29 05:29 UTC, merged