PR issue resolved
Redback-Operations/redback-senior-tech pull request #92
Opened 2024-09-08 11:39 UTC by Trissaan

## What are the changes?

 I have removed the files from the previous trimester and added code files on which the model will be built. 

## Who worked on the changes?

 I worked on the changes (s222596801 - Trissaan A Shanmugasundaram)

## New Components/Features

- Description of the dataset.
- Code file for data conversion 
- code file for data merging 
- code file for Data Preprocessing
- code file for Feature selection

## TODOs

 [x] Merging the dataset 
 [x] Dataset from txt to csv
 [x] Data Preprocessing
 [x] EDA
 [x] PCA (Feature Selection)
 [ ] Model creation 
 [ ] Testing and Cross-validation
 [ ] Finalising the Model

2024-09-11 08:36 UTC, Manan2711 reviewed
Hi Trissaan, just a couple of comments:
1. Can you please add a README file for documentation purposes, explaining what the folder is about, and how someone can navigate through the folder and run the code on their own devices?
2. Also in the `eda.ipynb` file you have done some analysis, can you please add comments or remarks on what the analysis reveals and how someone can interpret the results?

The files can be merged for now so that your teammates can sync with the progress made, but the changes need to be made before handover so that it will be easier for future teams to build upon this.

2024-09-11 08:36 UTC, Manan2711 commented on data_science/parkinsons_disease/code_files/txt_to_csv.ipynb
This file contains errors, can you please check and fix the error so that if someone wants to run the code in future, they can run it easily.

2024-09-11 08:36 UTC, Manan2711 commented on data_science/parkinsons_disease/data_format.txt
Can you please add this to a Markdown file instead?

2024-09-11 13:42 UTC, Trissaan commented on data_science/parkinsons_disease/data_format.txt
I changed the file format Manan

2024-09-11 13:42 UTC, Trissaan commented on data_science/parkinsons_disease/code_files/txt_to_csv.ipynb
I resolved the issues with the files Manan

2024-09-11 23:36 UTC, Manan2711 requested changes

2024-09-11 23:36 UTC, Manan2711 commented on data_science/parkinsons_disease/code_files/txt_to_csv.ipynb
Can you please remove the "os.getcwd()" output, as it's sensitive information, and personal directories shouldn't be printed in public repos. Thank you!

2024-09-13 04:18 UTC, Trissaan commented on data_science/parkinsons_disease/code_files/txt_to_csv.ipynb
I remove the cell Manan

2024-09-16 00:06 UTC, Manan2711 approved these changes
Everything looks good now, thank you for the changes!

2024-09-16 00:07 UTC, merged